# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
node1 ansible_ssh_host=9.59.68.15  # ip=10.3.0.1
node2 ansible_ssh_host=9.59.2.78  # ip=10.3.0.2
node3 ansible_ssh_host=9.59.19.72  # ip=10.3.0.3
# node4 ansible_ssh_host=95.54.0.15  # ip=10.3.0.4
# node5 ansible_ssh_host=95.54.0.16  # ip=10.3.0.5
# node6 ansible_ssh_host=95.54.0.17  # ip=10.3.0.6

# ## configure a bastion host if your nodes are not directly reachable
# bastion ansible_ssh_host=x.x.x.x

[kube-master]
node1

[etcd]
node1

[kube-node]
node1
node2
node3
# node4
# node5
# node6

[k8s-cluster:children]
kube-node
kube-master
